"use client";
import {useEffect,useMemo,useState} from "react";
import{ArrowRight,BarChart3,Check,ChevronRight,Clock3,Download,LockKeyhole,MoreHorizontal,Pause,Plus,RotateCcw,Settings2,ShieldCheck,Sparkles,Target,Trash2,Upload,X,Moon,Sun}from"lucide-react";
type Goal={id:string;label:string;icon:string;accent:string;startedAt:string;best:number;checkIns:number;resets:number;active:boolean;reason?:string};
type Checkin={date:string;goalId:string;stayedOnTrack:boolean};
const opts=[["Nicotine","N","red"],["Smoking","S","red"],["Vaping","V","blue"],["Alcohol","A","amber"],["Sugar / junk food","S","orange"],["Doomscrolling","D","violet"],["Social media","S","blue"],["Gaming","G","purple"],["Something else","•","slate"]] as const;
const dk=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const rg=(v:string|null):Goal[]=>{try{const a=JSON.parse(v||"[]");return Array.isArray(a)?a.filter(x=>x?.id&&x?.label).map(x=>({...x,best:+x.best||0,checkIns:+x.checkIns||0,resets:+x.resets||0,active:x.active!==false})):[]}catch{return[]}};
const rc=(v:string|null):Checkin[]=>{try{const a=JSON.parse(v||"[]");return Array.isArray(a)?a.filter(x=>typeof x?.goalId==="string"&&typeof x?.date==="string"):[]}catch{return[]}};
const hasTrack=(arr:Checkin[],goalId:string,date:string)=>arr.some(x=>x.goalId===goalId&&x.date===date&&x.stayedOnTrack);
const streakFor=(arr:Checkin[],goalId:string,startedAt:string)=>{const start=startedAt.slice(0,10),d=new Date();d.setHours(12,0,0,0);if(!hasTrack(arr,goalId,dk(d)))d.setDate(d.getDate()-1);let n=0;while(dk(d)>=start&&hasTrack(arr,goalId,dk(d))){n++;d.setDate(d.getDate()-1)}return n};
const bestStreakFor=(arr:Checkin[],goalId:string)=>{const dates=arr.filter(x=>x.goalId===goalId&&x.stayedOnTrack).map(x=>x.date).sort();let best=0,run=0,prev="";for(const date of dates){if(date===prev)continue;const p=prev?new Date(prev+"T12:00:00"):null,d=new Date(date+"T12:00:00");if(p&&Math.round((d.getTime()-p.getTime())/86400000)===1)run++;else run=1;best=Math.max(best,run);prev=date}return best};

export default function Home(){
const[g,setG]=useState<Goal[]>([]),[c,setC]=useState<Checkin[]>([]),[ready,setReady]=useState(false),[dark,setDark]=useState(false),[sel,setSel]=useState(""),[tab,setTab]=useState<"today"|"progress"|"settings">("today"),[intro,setIntro]=useState(false),[step,setStep]=useState(0),[pick,setPick]=useState<(typeof opts)[number]|null>(null),[reason,setReason]=useState(""),[sheet,setSheet]=useState<"goal"|"pause"|"reset"|null>(null),[timer,setTimer]=useState(600),[toast,setToast]=useState("");
const cur=g.find(x=>x.id===sel)||g[0],days=cur?streakFor(c,cur.id,cur.startedAt):0,best=cur?Math.max(cur.best,bestStreakFor(c,cur.id)):0,today=!!cur&&hasTrack(c,cur.id,dk()),checkIns=cur?c.filter(x=>x.goalId===cur.id&&x.stayedOnTrack).length:0,week=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-6+i);return dk(d)}),[]);
const wc=cur?week.filter(d=>hasTrack(c,cur.id,d)).length:0; const consistency=cur?Math.round((wc/7)*100):0; const nextMilestone=days<3?3:days<7?7:days<14?14:days<30?30:60; const timerDeg=Math.max(0,Math.min(360,(timer/600)*360)); const todayLabel=new Date().toLocaleDateString(undefined,{weekday:"long"}).toUpperCase();
useEffect(()=>{const a=rg(localStorage.getItem("quitify-goals")),b=rc(localStorage.getItem("quitify-checkins"));setG(a);setC(b);setSel(a[0]?.id||"");setIntro(!a.length);setDark(localStorage.getItem("quitify-theme")==="dark");setReady(true)},[]);
useEffect(()=>{if(ready)localStorage.setItem("quitify-goals",JSON.stringify(g))},[g,ready]);useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";if(ready)localStorage.setItem("quitify-theme",dark?"dark":"light")},[dark,ready]);useEffect(()=>{if(ready)localStorage.setItem("quitify-checkins",JSON.stringify(c))},[c,ready]);
useEffect(()=>{if(sheet!=="pause"||timer<1)return;const i=setInterval(()=>setTimer(v=>v-1),1000);return()=>clearInterval(i)},[sheet,timer]);
useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==="Escape"){setSheet(null);setIntro(false)}};addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[]);
const note=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
const create=(o:(typeof opts)[number],r="")=>{if(g.some(x=>x.label===o[0])){const existing=g.find(x=>x.label===o[0]);if(existing)setSel(existing.id);setSheet(null);setTab("today");note("Focus selected.");return}const id=crypto?.randomUUID?.()||Date.now().toString();setG(v=>[...v,{id,label:o[0],icon:o[1],accent:o[2],startedAt:new Date().toISOString(),best:0,checkIns:0,resets:0,active:true,reason:r}]);setSel(id);setIntro(false);setSheet(null);setTab("today");note("Focus added.")};
const selectGoal=(id:string)=>{setSel(id);setSheet(null);setTab("today");note("Focus changed.")};
const check=()=>{if(!cur)return;const d=dk(),n=!today;setC(v=>[...v.filter(x=>!(x.goalId===cur.id&&x.date===d)),{goalId:cur.id,date:d,stayedOnTrack:n}]);note(n?"Today is checked in.":"Today's check-in was removed.")};
const fresh=()=>{if(!cur)return;setG(v=>v.map(x=>x.id===cur.id?{...x,startedAt:new Date().toISOString(),best:Math.max(x.best,days),resets:x.resets+1}:x));setC(v=>v.filter(x=>!(x.goalId===cur.id&&x.date===dk())));setSheet(null);note("Fresh start saved.")};
const backup=()=>{const b=new Blob([JSON.stringify({version:3,exportedAt:new Date().toISOString(),goals:g,checkins:c},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="quitify-backup.json";a.click();note("Backup exported.")};
if(!ready)return <main className="loading"><span>Q</span><b>QUITify</b></main>;
return <main className="app"><div className="shell">
<header className="top"><button className="logo" onClick={()=>setTab("today")}><span>Q</span><strong>QUITify</strong></button><div className="topstatus"><ShieldCheck size={13}/><span>On-device</span></div><button className="topbtn" aria-label="Settings" onClick={()=>setTab("settings")}><Settings2 size={18}/></button></header>
{tab==="today"&&<section className="page"><div className="heading"><div><p>{todayLabel}</p><h1>Today</h1><span>One day at a time.</span></div><button className="round" onClick={()=>setSheet("goal")}><Plus size={18}/></button></div>
{cur?<div className="stack">
<section className="focus focushero"><div className="focusline"><i className={cur.accent}>{cur.icon}</i><div><small>YOUR FOCUS</small><b>{cur.label}</b>{cur.reason&&<small className="focusreason">Because: {cur.reason}</small>}</div><button onClick={()=>setSheet("goal")} aria-label="Change focus"><MoreHorizontal size={18}/></button></div><div className="run"><div><strong>{days}</strong><span>day{days===1?"":"s"} on your current run</span></div><div className="best"><small>Personal best</small><b>{best} days</b></div></div><div className="track"><i style={{width:`${Math.min(100,Math.max(8,(((days%7)||7)/7)*100))}%`}}/></div><div className="trackmeta"><span>Current run</span><span>{days%7===0&&days>0?"7-day milestone":`${7-(days%7)} days to next week`}</span></div>
</section><section className="today-insight"><div className="insight-mark"><Target size={16}/></div><div><p>YOUR WHY</p><b>{cur.reason||"You chose to make a change."}</b><span>{today?"You have already recorded today.":"A small decision today is enough."}</span></div></section>

<section className="check"><div className="checkintro"><div><p>TODAY</p><h2>{today?"You're on track.":"Check in with yourself."}</h2></div><span className={today?"done":""}>{today?"✓ Recorded":"A simple daily check-in"}</span></div><span className="checkcopy">{today?"Recorded for today. Keep going at your own pace.":"Record today without a score or judgment."}</span><button className={today?"checked":""} onClick={check}><i>{today&&<Check size={19}/>}</i><em><b>{today?"On track today":"I'm on track today"}</b><small>{today?"Tap to undo":"Tap to record"}</small></em><ChevronRight size={18}/></button><button className="moment" onClick={()=>{setTimer(600);setSheet("pause")}}><Pause size={14}/> I need a moment <ChevronRight size={14}/></button></section>
<section className="week"><div className="sectiontop"><div><p>LAST 7 DAYS</p><h3>Your week</h3></div><b>{wc}/7 on track</b></div><div className="weekrow">{week.map(d=>{const marked=c.some(x=>x.goalId===cur.id&&x.date===d&&x.stayedOnTrack),dt=new Date(d+"T12:00:00");return <div className={d===dk()?"today":""} key={d}><small>{dt.toLocaleDateString(undefined,{weekday:"short"}).slice(0,2)}</small><i className={marked?"on":""}>{marked?<Check size={12}/>:d===dk()?"":""}</i><em>{dt.getDate()}</em></div>})}</div><div className="weeklegend"><span><i className="done-dot"/>On track</span><span><i className="today-dot"/>Today</span></div></section>
<div className="actions"><button onClick={()=>{setTimer(600);setSheet("pause")}}><i><Clock3 size={16}/></i><span><b>Pause for 10 minutes</b><small>Create a little space before the next choice.</small></span><ChevronRight size={15}/></button><button onClick={()=>setSheet("reset")}><i><RotateCcw size={16}/></i><span><b>Reset today</b><small>Start a fresh run without deleting your history.</small></span><ChevronRight size={15}/></button></div>
</div>:<Empty onClick={()=>setSheet("goal")} text="Choose one thing to work on."/>}</section>}
{tab==="progress"&&<section className="page"><div className="heading"><div><p>PROGRESS</p><h1>Your progress</h1><span>See your consistency over time.</span></div></div>{cur?<div className="progress-stack"><section className="progress-hero"><div><p>YOUR CURRENT RUN</p><strong>{days}</strong><span>day{days===1?"":"s"} in a row</span></div><div className="hero-best"><small>PERSONAL BEST</small><b>{best} days</b></div></section><section className="week-progress"><div className="progress-section-head"><div><p>THIS WEEK</p><h3>{wc===0?"Your week is just getting started.":wc===7?"A full week on track.":"You're building a pattern."}</h3></div><b>{consistency}%</b></div><div className="consistency-line"><i style={{width:`${consistency}%`}}/></div><div className="week-bars">{week.map(d=>{const marked=c.some(x=>x.goalId===cur.id&&x.date===d&&x.stayedOnTrack),dt=new Date(d+"T12:00:00");return <div className={d===dk()?"current-day":""} key={d}><i className={marked?"on":d===dk()?"current":""}/><small>{dt.toLocaleDateString(undefined,{weekday:"short"}).slice(0,2)}</small></div>})}</div></section><div className="progress-metrics"><div><small>CHECK-INS</small><b>{c.filter(x=>x.goalId===cur.id).length}</b><span>all time</span></div><div><small>FRESH STARTS</small><b>{cur.resets}</b><span>in history</span></div></div><section className="history"><div className="progress-section-head"><div><p>LAST 14 DAYS</p><h3>Daily check-ins</h3></div><span>Last 14 days</span></div><div className="history-grid">{Array.from({length:14},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-13+i);const k=dk(d),m=c.some(x=>x.goalId===cur.id&&x.date===k&&x.stayedOnTrack),dt=new Date(k+"T12:00:00");return <div className={m?"on":k===dk()?"current":""} key={k}><b>{dt.getDate()}</b><span>{dt.toLocaleDateString(undefined,{weekday:"narrow"})}</span>{m&&<Check size={12}/>}</div>})}</div></section><section className="milestone"><div className="milestone-icon"><Target size={17}/></div><div><p>NEXT MILESTONE</p><b>{nextMilestone}-day consistency</b><span>{days>=nextMilestone?"Milestone reached. Your next chapter starts from here.":(nextMilestone-days)+" day"+(nextMilestone-days===1?"":"s")+" to go"}</span></div><div className="milestone-steps"><i className={days>=3?"reached":""}>3</i><i className={days>=7?"reached":""}>7</i><i className={days>=14?"reached":""}>14</i><i className={days>=30?"reached":""}>30</i></div></section></div>:<Empty onClick={()=>setSheet("goal")} text="Your progress will appear here."/>}</section>}
{tab==="settings"&&<section className="page"><div className="heading"><div><p>SETTINGS</p><h1>Your space</h1><span>Simple controls. Local data. Nothing extra.</span></div></div><div className="settings-wrap"><p className="settings-label">APPEARANCE</p><section className="settings"><button className="theme-row" onClick={()=>setDark(v=>!v)}><i>{dark?<Moon size={16}/>:<Sun size={16}/>}</i><span><b>Appearance</b><small>{dark?"Dark":"Light"} mode</small></span><span className={dark?"switch on":"switch"} aria-hidden="true"><i/></span></button></section><p className="settings-label">YOUR DATA</p><section className="settings"><div><i><LockKeyhole size={16}/></i><span><b>Private by default</b><small>Goals and check-ins stay on this device.</small></span><em>LOCAL</em></div><button onClick={backup}><i><Download size={16}/></i><span><b>Export backup</b><small>Save a copy of your QUITify data.</small></span><ChevronRight size={16}/></button><label><i><Upload size={16}/></i><span><b>Restore backup</b><small>Bring saved data back to this device.</small></span><ChevronRight size={16}/><input hidden type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x.goals))throw 0;setG(rg(JSON.stringify(x.goals)));setC(rc(JSON.stringify(x.checkins||[])));setSel(x.goals[0]?.id||"");note("Backup restored.")}catch{note("Backup could not be restored.")}}}/></label></section><p className="settings-label">ABOUT QUITIFY</p><section className="settings"><div><i><ShieldCheck size={16}/></i><span><b>Local-first & self-guided</b><small>Your data stays in this browser. QUITify is not medical treatment.</small></span></div></section><p className="settings-label">DANGER ZONE</p><section className="settings danger-card"><button className="danger" onClick={()=>{localStorage.removeItem("quitify-goals");localStorage.removeItem("quitify-checkins");localStorage.removeItem("quitify-theme");setG([]);setC([]);setSel("");setIntro(true);setStep(0);note("Local data cleared.")}}><Trash2 size={16}/><span><b>Clear local data</b><small>Delete QUITify goals and check-ins from this browser.</small></span></button></section></div></section>}
<nav className="nav"><button className={tab==="today"?"active":""} onClick={()=>setTab("today")}><Target size={18}/><span>Today</span></button><button className={tab==="progress"?"active":""} onClick={()=>setTab("progress")}><BarChart3 size={18}/><span>Progress</span></button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}><Settings2 size={18}/><span>Settings</span></button></nav>
{intro&&<div className="modal onboarding-modal" role="dialog" aria-modal="true" aria-label="QUITify setup"><div className="onboard-v2"><header className="onboard-top"><button className="logo" onClick={()=>{setIntro(false);setStep(0)}}><span>Q</span><strong>QUITify</strong></button><div className="onboard-top-actions"><div className="on-progress" aria-label={`Step ${step+1} of 3`}>{[0,1,2].map(i=><i className={i<=step?"active":""} key={i}/>)}</div><button className="on-skip" onClick={()=>{setIntro(false);setStep(0)}}>Skip</button></div></header><div className="onboard-content">{step===0&&<div className="on-screen on-welcome"><div className="on-hero-mark"><Sparkles size={22}/></div><p className="on-kicker">A PRIVATE RESET SPACE</p><h1>Make room for the<br/><em>next choice.</em></h1><p className="on-lead">QUITify helps you change one habit at a time — without scores, feeds, or judgment.</p><div className="on-preview"><div className="preview-dot"><Check size={15}/></div><div><b>Today, not forever.</b><span>See one clear next step when you open the app.</span></div><ChevronRight size={16}/></div><div className="on-footer"><button className="primary on-primary" onClick={()=>setStep(1)}>Choose my focus <ArrowRight size={16}/></button><small>About 30 seconds to set up</small></div></div>}{step===1&&<div className="on-screen"><div className="on-heading"><p className="on-kicker">STEP 1 OF 2</p><h1>What do you want<br/>more control over?</h1><p className="on-lead">Pick one. You can add another focus later.</p></div><div className="options-v2">{opts.map(o=><button className={pick?.[0]===o[0]?"selected":""} key={o[0]} onClick={()=>setPick(o)}><i className={o[2]}>{o[1]}</i><span>{o[0]}</span>{pick?.[0]===o[0]?<Check size={17}/>:<ChevronRight size={16}/>}</button>)}</div><div className="on-footer"><button className="primary on-primary" disabled={!pick} onClick={()=>setStep(2)}>Continue <ArrowRight size={16}/></button><button className="on-back" onClick={()=>setStep(0)}>Back</button></div></div>}{step===2&&<div className="on-screen"><div className="on-heading"><p className="on-kicker">STEP 2 OF 2</p><h1>Why does this<br/>matter to you?</h1><p className="on-lead">Optional. This gives your goal a reason to come back to.</p></div><div className="reasons-v2">{["More focus","More time","Better sleep","My relationships","More money","Just for me"].map(r=><button className={reason===r?"selected":""} key={r} onClick={()=>setReason(r)}><span>{r}</span>{reason===r&&<Check size={17}/>}</button>)}</div><div className="on-footer"><button className="primary on-primary" onClick={()=>pick&&create(pick,reason)}>Start with QUITify <ArrowRight size={16}/></button><button className="on-back" onClick={()=>pick&&create(pick)}>Skip this question</button></div></div>}</div></div></div>}
{sheet&&<div className="overlay" onClick={()=>setSheet(null)}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="handle"/>{sheet==="goal"&&<><div className="sheethead"><div><p>FOCUS</p><h2>{cur?"Choose a focus":"Choose your focus"}</h2></div><button className="sheet-close" aria-label="Close" onClick={()=>setSheet(null)}><X size={18}/></button></div>{g.length>0&&<><p className="sheetlabel">YOUR FOCUSES</p><div className="sheetopts focus-existing">{g.map(o=><button className={o.id===cur?.id?"selected":""} key={o.id} onClick={()=>selectGoal(o.id)}><i className={o.accent}>{o.icon}</i><span>{o.label}<small>{o.reason||"Focus"}</small></span>{o.id===cur?.id?<Check size={17}/>:<ChevronRight size={16}/>}</button>)}</div></>}<p className="sheetlabel">{g.length>0?"ADD ANOTHER FOCUS":"CHOOSE A FOCUS"}</p><div className="sheetopts">{opts.filter(o=>!g.some(x=>x.label===o[0])).map(o=><button key={o[0]} onClick={()=>create(o)}><i className={o[2]}>{o[1]}</i><span>{o[0]}</span><ChevronRight size={16}/></button>)}</div></>}{sheet==="pause"&&<div className="pause-screen"><div className="pause-top"><div><p>TAKE A MOMENT</p><h2>Give yourself<br/>ten minutes.</h2></div><button onClick={()=>setSheet(null)}><X size={18}/></button></div><div className={timer===0?"pause-clock complete":"pause-clock"}><div className="clock-ring" style={{background:`conic-gradient(var(--accent) 0deg, var(--accent) ${timerDeg}deg, rgba(53,92,222,.12) ${timerDeg}deg 360deg)`}}><span>{String(Math.floor(timer/60)).padStart(2,"0")}:{String(timer%60).padStart(2,"0")}</span></div><p>{timer===0?"Ten minutes are up. You made some space; return when you’re ready.":"The decision can wait. You don’t have to solve anything right now."}</p></div><div className="pause-steps"><div><span>01</span><div><b>Change the scene</b><small>Stand up, move rooms, or step away from the screen.</small></div></div><div><span>02</span><div><b>Do something ordinary</b><small>Drink water, stretch, tidy something, or return to a simple task.</small></div></div></div><button className="primary pause-done" onClick={()=>setSheet(null)}>{timer===0?"Back to today":"I'm ready"} <ArrowRight size={16}/></button></div>}{sheet==="reset"&&<><div className="sheethead"><div><p>FRESH START</p><h2>Start again without erasing your history.</h2></div><button onClick={()=>setSheet(null)}><X size={18}/></button></div><span className="copy">Your previous best and check-ins remain saved. Only the current run starts over.</span><div className="reset"><button onClick={()=>setSheet(null)}>Keep my run</button><button className="primary" onClick={fresh}>Start fresh <RotateCcw size={15}/></button></div></>}</section></div>}
{toast&&<div className="toast"><Check size={14}/>{toast}</div>}
</div></main>
}
function Empty({onClick,text}:{onClick:()=>void;text:string}){return <section className="empty"><i><Target size={24}/></i><p>START HERE</p><h2>{text}</h2><span>One goal, one day, one check-in at a time.</span><button className="primary" onClick={onClick}>Choose my focus <ArrowRight size={16}/></button></section>}
